actors:
  YutaYoshida:
    image_url: /images/actors/yutatatatata.jpeg
    name: YutaYoshida
    url: https://twitter.com/yutatatatata
  AkikoSuyari:
    image_url: /images/actors/alice.png
    name: AkikoSuyari
    url: 
  KojiSato:
    image_url: /images/actors/KojiSato.jpg
    name: ä½è—¤å…‰å¸
    url: https://www.facebook.com/profile.php?id=100013102029008
  UtsunomiyaMasataka:
    image_url: /images/actors/UtsunomiyaMasataka.png
    name: å®‡éƒ½å®®é›…æ•¬
    url: https://www.facebook.com/masataka.utsunomiya.9
  KanakoAke:
    image_url: /images/actors/KanakoAke.jpg
    name: å®‰å®¶å¶å­
    url: https://www.facebook.com/profile.php?id=100004529610782
  HirokiYoshida:
    image_url: /images/actors/alice.jpg
    name: å‰ç”°æµ©æ°—
    url: https://www.instagram.com/pain_cailloux/
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
author: NewKamer.fm
description: ã€Œã“ã®è¡—ã®é¢ç™½ã„äººãŸã¡ã‚’ç´¹ä»‹ã—ãŸã„ãœãƒƒï¼inéŒå€‰ãƒ»æ¹˜å—ç•Œéšˆã€ãŒãƒ¢ãƒãƒ™ãƒ¼ã‚·ãƒ§ãƒ³ã®ãƒ­ãƒ¼ã‚«ãƒ«ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆç•ªçµ„ã§ã™ğŸŒŠ
description_long: éŒå€‰ãƒ»æ¹˜å—ç•Œéšˆã®ãƒ¦ãƒ‹ãƒ¼ã‚¯ãªäººãŸã¡ã¨æ°—ã¾ã¾ã«ãŠã—ã‚ƒã¹ã‚Šã™ã‚‹ãƒ­ãƒ¼ã‚«ãƒ«ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã§ã™ã€‚
email: newkamer.fm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: newkamerfm
itunes_podcast_url: https://podcasts.apple.com/us/podcast/newkamer-fm/id1715877310
keywords: éŒå€‰, æ¹˜å—, Podcast
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: NewKamer.fm
url: https://newkamer.github.io/
