actors:
  YutaYoshida:
    image_url: /images/actors/yutatatatata.jpeg
    name: YutaYoshida
    url: https://twitter.com/yutatatatata
  akiko:
    image_url: /images/actors/alice.png
    name: akiko
    url: 
  KojiSato:
    image_url: /images/actors/KojiSato.jpg
    name: 佐藤光司
    url: https://www.facebook.com/profile.php?id=100013102029008
  UtsunomiyaMasataka:
    image_url: /images/actors/UtsunomiyaMasataka.png
    name: 宇都宮雅敬
    url: https://www.facebook.com/masataka.utsunomiya.9
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
author: NewKamer.fm
description: 鎌倉・湘南界隈のユニークな人たちと気ままにおしゃべりするローカルPodcastです
description_long: 鎌倉・湘南界隈のユニークな人たちと気ままにおしゃべりするローカルPodcastです。いつか鎌倉にクラフトビールxPodcastのお店を開くことが目標！
email: newkamer.fm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: newkamerfm
itunes_podcast_url: https://podcasts.apple.com/us/podcast/newkamer-fm/id1715877310
keywords: 鎌倉, 湘南, Podcast
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: NewKamer.fm
url: https://newkamer.github.io/
